Topics for revision:
    
    Numpy
    Pandas
    Importing and exporting data
    Matplotlib and Seaborn
    Data Portfolio projects
    Machine Learning with Scikit-Learn
    Statistics
    SQL with python
    Web Scraping with python


Import numpy library

In [1]:
import numpy as np

create arrays

In [3]:
my_list1 = [1,2,3,4,]
my_list2 = [11,22,33,44]

In [4]:
my_array1 = np.array(my_list1)
my_array2 = np.array(my_list2)

In [5]:
print(my_array1)
print(my_array2)

[1 2 3 4]
[11 22 33 44]


In [6]:
my_arrays = my_array1+my_array2

In [7]:
my_arrays # you can add arrays

array([12, 24, 36, 48])

Now we can make multi-dimensional array using both lists

In [8]:
my_lists = [my_list1, my_list2]

In [9]:
my_array2 = np.array(my_lists)

In [10]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

Get some info about the created matrix

In [11]:
my_array2.shape #2 rows and 4 columns

(2, 4)

In [17]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
np.ones(10).reshape(5,2)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [20]:
np.ones([4,6])

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [21]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [22]:
np.eye(5) #identical matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Another way of creating arrays using arange

In [23]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [25]:
np.arange(5,30,3)

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29])

In [27]:
np.arange(5,30,3).reshape(3,3)

array([[ 5,  8, 11],
       [14, 17, 20],
       [23, 26, 29]])

---

Using arrays and scalars

In [30]:
arr1 = np.array([[1,2,3,4],[8,9,10,11]])

In [31]:
arr1

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [32]:
arr1*arr1

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [33]:
arr1+arr1

array([[ 2,  4,  6,  8],
       [16, 18, 20, 22]])

In [34]:
arr1-arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [36]:
1/arr1

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.125     , 0.11111111, 0.1       , 0.09090909]])

In [37]:
arr1/5

array([[0.2, 0.4, 0.6, 0.8],
       [1.6, 1.8, 2. , 2.2]])

In [38]:
arr1**3

array([[   1,    8,   27,   64],
       [ 512,  729, 1000, 1331]], dtype=int32)

---

Indexing Arrays

In [41]:
arr = np.arange(0,12)

In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [45]:
arr[8]

8

In [46]:
arr[1:5]

array([1, 2, 3, 4])

In [47]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [48]:
arr[0:5] = 100

In [49]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11])

In [60]:
arr2 = arr.reshape(4,3)

In [61]:
arr2

array([[100, 100, 100],
       [100, 100,   5],
       [  6,   7,   8],
       [  9,  10,  11]])

In [62]:
arr2[0]

array([100, 100, 100])

In [63]:
arr2[3]

array([ 9, 10, 11])

In [66]:
arr2[2,2]

8

In [67]:
arr2[3,1]

10

In [68]:
arr2[:]

array([[100, 100, 100],
       [100, 100,   5],
       [  6,   7,   8],
       [  9,  10,  11]])

In [69]:
arr2[:,:]

array([[100, 100, 100],
       [100, 100,   5],
       [  6,   7,   8],
       [  9,  10,  11]])

In [70]:
arr2[:-1]

array([[100, 100, 100],
       [100, 100,   5],
       [  6,   7,   8]])

In [71]:
arr2[-1:]

array([[ 9, 10, 11]])

In [73]:
arr2[::-1]

array([[  9,  10,  11],
       [  6,   7,   8],
       [100, 100,   5],
       [100, 100, 100]])

In [74]:
arr2[::-1,::-1]

array([[ 11,  10,   9],
       [  8,   7,   6],
       [  5, 100, 100],
       [100, 100, 100]])

In [76]:
arr2.ndim #number of dimensions

2

In [77]:
arr2[::,::]

array([[100, 100, 100],
       [100, 100,   5],
       [  6,   7,   8],
       [  9,  10,  11]])

In [78]:
arr2[::2]

array([[100, 100, 100],
       [  6,   7,   8]])

In [79]:
arr2[:-2]

array([[100, 100, 100],
       [100, 100,   5]])

In [80]:
arr2

array([[100, 100, 100],
       [100, 100,   5],
       [  6,   7,   8],
       [  9,  10,  11]])

In [81]:
arr2[:]

array([[100, 100, 100],
       [100, 100,   5],
       [  6,   7,   8],
       [  9,  10,  11]])

In [82]:
arr2[::]

array([[100, 100, 100],
       [100, 100,   5],
       [  6,   7,   8],
       [  9,  10,  11]])

In [83]:
arr2[::,::]

array([[100, 100, 100],
       [100, 100,   5],
       [  6,   7,   8],
       [  9,  10,  11]])

In [87]:
arr3 = np.arange(0,27)

In [91]:
arr3 = arr3.reshape(3,3,3)

In [92]:
arr3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [93]:
arr3.ndim

3

In [94]:
arr3[:]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [95]:
arr3[::]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [96]:
arr3[:,:]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [97]:
arr3[::,::]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [98]:
arr3[::,::,::]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [102]:
arr3[::-1,::,::]#rows are reversed

array([[[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]]])

In [103]:
arr3[::-1,::-1,::]#rows within rows are reversed

array([[[24, 25, 26],
        [21, 22, 23],
        [18, 19, 20]],

       [[15, 16, 17],
        [12, 13, 14],
        [ 9, 10, 11]],

       [[ 6,  7,  8],
        [ 3,  4,  5],
        [ 0,  1,  2]]])

In [104]:
arr3[::-1,::-1,::-1]#columsn with rows within rows are reversed

array([[[26, 25, 24],
        [23, 22, 21],
        [20, 19, 18]],

       [[17, 16, 15],
        [14, 13, 12],
        [11, 10,  9]],

       [[ 8,  7,  6],
        [ 5,  4,  3],
        [ 2,  1,  0]]])

In [113]:
slice_of_array = arr2[0:2]

In [114]:
slice_of_array

array([[100, 100, 100],
       [100, 100,   5]])

In [115]:
slice_of_array[:] = 36

In [116]:
arr2

array([[36, 36, 36],
       [36, 36, 36],
       [ 6,  7,  8],
       [ 9, 10, 11]])

it is clear that slicing of arrays only provide view of original array and hence amanipulating slice also manipulates the original. hence it is important to explicitly make a copy if needed.

In [117]:
arr_copy = arr.copy()

In [118]:
arr_copy

array([36, 36, 36, 36, 36, 36,  6,  7,  8,  9, 10, 11])

In [120]:
arr_copy[:] = 1

In [121]:
arr_copy

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [122]:
arr

array([36, 36, 36, 36, 36, 36,  6,  7,  8,  9, 10, 11])

In [123]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

In [124]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [125]:
arr_2d[1]

array([20, 25, 30])

In [126]:
arr_2d[2]

array([35, 40, 45])

In [127]:
arr_2d[0][2]

15

In [128]:
arr_2d[1][-1]

30

In [129]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [130]:
arr_2d[1:,1:]

array([[25, 30],
       [40, 45]])

In [133]:
arr2d = np.zeros((10,10))

In [134]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [137]:
arr2d.shape[1]

10

In [140]:
arr2d[:]= 1

In [141]:
arr2d

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [142]:
for i in range(arr2d.shape[1]):
    arr2d[i] = i

In [143]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [144]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [145]:
arr2d[[6,4,1,9]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])