In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [4]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
ser1 = Series ([0,1,2],index=['T','U','V'])
ser2 = Series ([3,4,5],index=['X','Y','W'])

In [7]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
W    5
dtype: int64

In [8]:
pd.concat([ser1,ser2],axis=1)

C:\Users\SP\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
W  NaN  5.0
X  NaN  3.0
Y  NaN  4.0

In [9]:
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
      W    5
dtype: int64

In [10]:
dframe1 = DataFrame(np.random.randn(4,3),columns=['X','Y','Z'])

dframe2 = DataFrame(np.random.randn(3,3),columns=['Y','Q','X'])

In [11]:
dframe1

X         Y         Z
0 -1.974974  0.273271 -1.901837
1  0.991259 -1.300637 -2.064219
2 -1.739321  0.266286 -0.544659
3  0.475422  0.635068 -1.618588

In [12]:
dframe2

Y         Q         X
0  0.899348 -0.329225  1.310864
1 -1.943035 -0.480407 -1.491825
2 -0.934126 -0.097029  0.485514

In [15]:
pd.concat([dframe1,dframe2])

C:\Users\SP\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


Q         X         Y         Z
0       NaN -1.974974  0.273271 -1.901837
1       NaN  0.991259 -1.300637 -2.064219
2       NaN -1.739321  0.266286 -0.544659
3       NaN  0.475422  0.635068 -1.618588
0 -0.329225  1.310864  0.899348       NaN
1 -0.480407 -1.491825 -1.943035       NaN
2 -0.097029  0.485514 -0.934126       NaN

In [16]:
pd.concat([dframe1,dframe2],ignore_index=True)

C:\Users\SP\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


Q         X         Y         Z
0       NaN -1.974974  0.273271 -1.901837
1       NaN  0.991259 -1.300637 -2.064219
2       NaN -1.739321  0.266286 -0.544659
3       NaN  0.475422  0.635068 -1.618588
4 -0.329225  1.310864  0.899348       NaN
5 -0.480407 -1.491825 -1.943035       NaN
6 -0.097029  0.485514 -0.934126       NaN